export const START_GET_USERNAME = "START_GET_USERNAME";
export const SUCCESSFUL_GET_USERNAME = "SUCCESSFUL_GET_USERNAME";
export const ERROR_GET_USERNAME = "ERROR_GET_USERNAME";
export const SET_WS_CONNECTION = "SET_WS_CONNECTION";
export const SET_CHAT_MESSAGES = "SET_CHAT_MESSAGES";
export const SET_WS_ERROR = "SET_WS_ERROR";

